FptLearningSystem/Areas/Administrator/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using FptLearningSystem.Data;
using FptLearningSystem.Models;
using FptLearningSystem.Models.ViewModels;
using FptLearningSystem.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FptLearningSystem.Areas.Administrator.Controllers
{
    [Authorize(Roles = SD.Administrator)]
    [Area("Administrator")]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CoursesController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        [TempData]
        public string StatusMessage { get; set; }

        //GET :: INDEX
        public async Task<IActionResult> Index()
        {
            var courses = await _db.Courses.Include(c => c.Category).ToListAsync();
            return View(courses);
        }

        //GET :: CREATE
        public async Task<IActionResult> Create()
        {
            CourseAndCategoryViewModel model = new CourseAndCategoryViewModel()
            {
                CaterotyList = await _db.Categories.ToListAsync(),
                Course = new Models.Course(),
                CourseList = await _db.Courses.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync()
            };

            return View(model);
        }

        //POST :: CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseAndCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesCourseExists = _db.Courses.Include(s => s.Category)
                    .Where(c => c.Name == model.Course.Name && c.Category.Id == model.Course.CategoryId);

                if (doesCourseExists.Count() > 0)
                {
                    //Error
                    StatusMessage = "Error: Course exists under " + doesCourseExists.First().Category.Name + " category. Please use another name.";
                }
                else
                {
                    _db.Courses.Add(model.Course);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            CourseAndCategoryViewModel modelVM = new CourseAndCategoryViewModel()
            {
                CaterotyList = await _db.Categories.ToListAsync(),
                Course = model.Course,
                CourseList = await _db.Courses.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage
                
            };
            return View(modelVM);
        }

        [ActionName("GetCourse")]
        public async Task<IActionResult> GetCourse(int id)
        {
            List<Course> courses = new List<Course>();

            courses = await (from Course in _db.Courses
                       where Course.CategoryId == id
                       select Course).ToListAsync();

            return Json(new SelectList(courses, "Id", "Name"));
        }

        //GET :: EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _db.Courses.SingleOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            CourseAndCategoryViewModel model = new CourseAndCategoryViewModel()
            {
                CaterotyList = await _db.Categories.ToListAsync(),
                Course = course,
                CourseList = await _db.Courses.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync()
            };

            return View(model);
        }

        //POST :: EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CourseAndCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesCourseExists = _db.Courses.Include(s => s.Category)
                    .Where(c => c.Name == model.Course.Name && c.Category.Id == model.Course.CategoryId);

                if (doesCourseExists.Count() > 0 && doesCourseExists.First().Name != _db.Courses.First().Name)
                {
                    //Error
                    StatusMessage = "Error: Course exists under " + doesCourseExists.First().Category.Name + " category. Please use another name.";
                }
                else
                {
                    var courseFromDb = await _db.Courses.FindAsync(model.Course.Id);
                    courseFromDb.Name = model.Course.Name;
                    courseFromDb.Description = model.Course.Description;

                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            CourseAndCategoryViewModel modelVM = new CourseAndCategoryViewModel()
            {
                CaterotyList = await _db.Categories.ToListAsync(),
                Course = model.Course,
                CourseList = await _db.Courses.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage

            };

            return View(modelVM);
        }

        //GET :: DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _db.Courses.Include(s => s.Category).SingleOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        //POST :: DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            var course = await _db.Courses.FindAsync(id);

            if (course == null)
            {
                return View();
            }
            _db.Courses.Remove(course);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

FptLearningSystem/Areas/Administrator/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FptLearningSystem.Data;
using FptLearningSystem.Models;
using FptLearningSystem.Models.ViewModels;
using FptLearningSystem.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FptLearningSystem.Areas.Administrator.Controllers
{
    [Authorize(Roles = SD.Administrator)]
    [Area("Administrator")]
    public class TopicsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public TopicsController(ApplicationDbContext db)
        {
            _db = db;
        }

        [TempData]
        public string StatusMessage { get; set; }

        //GET :: INDEX
        public async Task<IActionResult> Index()
        {
            var topics = await _db.Topics.Include(c => c.Course).ToListAsync();
            return View(topics);
        }

        //GET :: CREATE
        public async Task<IActionResult> Create()
        {
            TopicAndCourseViewModel model = new TopicAndCourseViewModel()
            {
                CourseList = await _db.Courses.ToListAsync(),
                Topic = new Models.Topic(),
                TopicList = await _db.Topics.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync()
            };

            return View(model);
        }

        //POST :: CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TopicAndCourseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesTopicExists = _db.Topics.Include(s => s.Course)
                    .Where(c => c.Name == model.Topic.Name && c.Course.Id == model.Topic.CourseId);

                if (doesTopicExists.Count() > 0)
                {
                    //Error
                    StatusMessage = "Error: Topic exists under " + doesTopicExists.First().Course.Name + " course. Please use another name.";
                }
                else
                {
                    _db.Topics.Add(model.Topic);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            TopicAndCourseViewModel modelVM = new TopicAndCourseViewModel()
            {
                CourseList = await _db.Courses.ToListAsync(),
                Topic = model.Topic,
                TopicList = await _db.Topics.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage

            };
            return View(modelVM);
        }

        [ActionName("GetTopic")]
        public async Task<IActionResult> GetTopic(int id)
        {
            List<Topic> topics = new List<Topic>();

            topics = await (from Topic in _db.Topics
                             where Topic.CourseId == id
                             select Topic).ToListAsync();

            return Json(new SelectList(topics, "Id", "Name"));
        }

        //GET :: EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _db.Topics.SingleOrDefaultAsync(m => m.Id == id);

            if (topic == null)
            {
                return NotFound();
            }

            TopicAndCourseViewModel model = new TopicAndCourseViewModel()
            {
                CourseList = await _db.Courses.ToListAsync(),
                Topic = topic,
                TopicList = await _db.Topics.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync()
            };

            return View(model);
        }

        //POST :: EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TopicAndCourseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesTopicExists = _db.Topics.Include(s => s.Course)
                    .Where(c => c.Name == model.Topic.Name && c.Course.Id == model.Topic.CourseId);

                if (doesTopicExists.Count() > 0 && doesTopicExists.First().Name != _db.Topics.First().Name)
                {
                    //Error
                    StatusMessage = "Error: Topic exists under " + doesTopicExists.First().Course.Name + " course. Please use another name.";
                }
                else
                {
                    var topicFromDb = await _db.Topics.FindAsync(model.Topic.Id);
                    topicFromDb.Name = model.Topic.Name;
                    topicFromDb.Description = model.Topic.Description;

                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            TopicAndCourseViewModel modelVM = new TopicAndCourseViewModel()
            {
                CourseList = await _db.Courses.ToListAsync(),
                Topic = model.Topic,
                TopicList = await _db.Topics.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage

            };

            return View(modelVM);
        }

        //GET :: DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var topic = await _db.Topics.Include(s => s.Course).SingleOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        //POST :: DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            var topic = await _db.Topics.FindAsync(id);

            if (topic == null)
            {
                return View();
            }
            _db.Topics.Remove(topic);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

FptLearningSystem/Areas/Administrator/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FptLearningSystem.Data;
using FptLearningSystem.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FptLearningSystem.Areas.Administrator.Controllers
{
    [Authorize(Roles = SD.Administrator)]
    [Area("Administrator")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UsersController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claimIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var users = await _db.ApplicationUsers.Where(u => u.Id != claim.Value).ToListAsync();

            return View(users);
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUsers
                .FirstOrDefaultAsync(m => m.Id == id);

            if(applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUsers
                .FirstOrDefaultAsync(m => m.Id == id);

            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

FptLearningSystem/Views/Shared/_AssignAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Assign" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FptLearningSystem/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Add" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FptLearningSystem/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FptLearningSystem/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-Id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

FptLearningSystem/Views/Shared/_Layout.cshtml
@using FptLearningSystem.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FptLearningSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/ce2572679b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom mb-3" id="opacityNew">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="Authenticated" asp-controller="AuthenticatedHome" asp-action="Index">
                        <label class="text-info" style="cursor:pointer">FptLearningSystem</label>
                    </a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="Unauthenticated" asp-controller="Home" asp-action="Index">
                        <label class="text-info" style="cursor:pointer">FptLearningSystem</label>
                    </a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(SD.TrainingStaff) || (User.IsInRole(SD.Administrator)))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownContentLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownContentLink" id="opacityOld">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Categories" asp-area="Authenticated">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Courses" asp-area="Authenticated">Course</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Topics" asp-area="Authenticated">Topic</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownUserLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User Management
                                </a>
                                <div class="dropdown-menu" id="opacityOld" aria-labelledby="navbarDropDownUserLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Users" asp-area="Authenticated">Users</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="TrainerTopics" asp-area="Authenticated">Assign Trainer</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="TraineeCourses" asp-area="Authenticated">Assign Trainee</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40;">
        <div class="container">
            &copy; 2020 - FptLearningSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FptLearningSystem/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

FptLearningSystem/Views/Shared/_TableButton.cshtml
@model int

<td>
    <div class="btn btn-group" style="display:inline-block" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <form class="btn-group" style="margin-top:16px;" role="group" method="post">
            <button style="border-bottom-right-radius: 5px; border-top-right-radius: 5px;" onclick="return confirm('Do you want to delete?')" type="submit" class="btn btn-danger" asp-action="Delete" asp-route-Id="@Model">
                <i class="fas fa-trash-alt"></i>
            </button>
        </form>
    </div>
</td>